### PR TITLE
add support for vue-tsc 2.0.1

### LINKED ISSUE #306: Stopped working with vue-tsc 2.0.1
### Describe the bug

Since file structuring changed in vue-tsc 2+, checker plugin no longer works as it expects file being in the exact location:

```
Error: Cannot find module 'vue-tsc/out/index'
Require stack:
- /home/runner/work/pikeo-web/pikeo-web/src/frontend/node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/prepareVueTsc.js
...
```

### Reproduction

Install checker plugin, vue-tsc 2.0.1 and enable vueTsc checker.

### Expected behavior

Plugin works.

### System Info

```shell
N/A. Sorry, filling this issue on my phone since I've noticed the issue in my CI build after dependabot update.
```

### Additional context

_No response_

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by simensfo**
resolves #306

### CODE REVIEW

**Comment by fi3ework** [comment]
it's not easy to solve the issue by this way, vue-tsc 2 changed a lot. We need to figure out a new way to integrate with it.

**Comment by simensfo** [comment]
I may be wrong, but based on the changelog there aren't really any breaking changes. If this plugin mostly just runs `vue-tsc` during build, then wouldn't it be enough to just import from the right place?

**Comment by armano2** [comment]
build part should be working fine even without this change, issue is with what is done during "patching" of lib
