### ISSUE TITLE
Does not work with "tiny-invariant": "^1.1.0"

### ISSUE THREAD

**Issue by rmisiakexscientia** [fi3ework/vite-plugin-checker#242]
### Describe the bug

The package.json for this package lists 
```
"tiny-invariant": "^1.1.0",
```
https://github.com/fi3ework/vite-plugin-checker/blob/main/package.json#LL105C7-L105C7

However if you have 1.1.0 installed then trying to run an application using the package gives the following error

```
error when starting dev server:
Error: _tiny_invariant.default is not a function
```

Upgrading to 1.2.0 or later works 

### Reproduction

https://stackblitz.com/edit/vitejs-vite-gelwns?file=package.json

### Expected behavior

The package works 

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vite-plugin-checker: latest => 0.6.0 
```

Also happens on node18
```


### Additional context

_No response_

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
