### ISSUE TITLE
Type error: Cannot find module 'vscode-languageserver/node'

### ISSUE THREAD

**Issue by danielrentz** [fi3ework/vite-plugin-checker#460]
### Describe the bug

```txt
node_modules/vite-plugin-checker/dist/checkers/vls/initParams.d.ts:2:34 - error TS2307: Cannot find module 'vscode-languageserver/node' or its corresponding type declarations.
2 import { InitializeParams } from 'vscode-languageserver/node';
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error in node_modules/vite-plugin-checker/dist/checkers/vls/initParams.d.ts:2
```

### Reproduction

Import "vite-plugin-checker" in a vite.config.ts, disable "skipLibCheck", run tsc on vite.config.ts

### Expected behavior

no type error

### System Info

```shell
Node 22.14, TS 5.7.3, checker 0.9.0
```

### Additional context

Seems to be caused by https://github.com/fi3ework/vite-plugin-checker/commit/fc0bcd6

### Validations

- [x] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by davidenke** [comment]
> ### Additional context
> Seems to be caused by [fc0bcd6](https://github.com/fi3ework/vite-plugin-checker/commit/fc0bcd6)

The issue disappears when rolling back `vite-plugin-checker` to `0.8.0`, so this change seems to be the culprit.
