### PR TITLE
fix: compatibility with vue-tsc 2.x

### LINKED ISSUE #306: Stopped working with vue-tsc 2.0.1
### Describe the bug

Since file structuring changed in vue-tsc 2+, checker plugin no longer works as it expects file being in the exact location:

```
Error: Cannot find module 'vue-tsc/out/index'
Require stack:
- /home/runner/work/pikeo-web/pikeo-web/src/frontend/node_modules/vite-plugin-checker/dist/esm/checkers/vueTsc/prepareVueTsc.js
...
```

### Reproduction

Install checker plugin, vue-tsc 2.0.1 and enable vueTsc checker.

### Expected behavior

Plugin works.

### System Info

```shell
N/A. Sorry, filling this issue on my phone since I've noticed the issue in my CI build after dependabot update.
```

### Additional context

_No response_

### Validations

- [X] Read the [docs](https://github.com/fi3ework/vite-plugin-checker#readme).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by so1ve**
fixes #306, close #321

~~This is a naive fix - it may cause problems described in https://github.com/fi3ework/vite-plugin-checker/issues/306#issuecomment-1974890034, but it will avoid crashes.~~

~~I'm still working on a complete solution.~~

~~Fixed, but requires installing `@vue/language-core` as a dependency, which may cause version mismatch.~~

Ran e2e tests locally and passed, the ci is failing due to d ts building issues and low nodejs version

### CODE REVIEW

File: packages/vite-plugin-checker/src/checkers/vueTsc/languagePlugins.js [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    (id) => id,
+    () => '',
+    (fileName) => {
+      const fileMap = new vue.FileMap(options.host?.useCaseSensitiveFileNames?.() ?? false)
+      for (const vueFileName of options.rootNames.map((rootName) =>
+        rootName.replace(windowsPathReg, '/')
+      )) {
+        fileMap.set(vueFileName, undefined)
+      }
+      return fileMap.has(fileName)
```
Comment (Simon-He95) [inline packages/vite-plugin-checker/src/checkers/vueTsc/languagePlugins.js:29]: Why not return directly in for?
I think it's will be faster
```
return fileMap.has(fileName) || options.rootNames.some(rootName => rootName.replace(windowsPathReg, '/') === fileName)
```

Comment (so1ve) [reply packages/vite-plugin-checker/src/checkers/vueTsc/languagePlugins.js:29]: Yeah but I'd like to keep it synched with upstream

**Comment by fi3ework** [comment]
I checked the PR code and found `vscode-uri` blocks `test:unit`. It has been bumped to `3.0.8` in lockfile and the type exports has been fixed. We could change `https://github.com/fi3ework/vite-plugin-checker/blob/0a2a2e04a79bfb90c38f1458467c749978c7cdbb/packages/vite-plugin-checker/src/checkers/vls/diagnostics.ts#L27` to normal write up.

File: packages/vite-plugin-checker/src/checkers/vueTsc/languagePlugins.js (hunk 1 above)
Comment (so1ve) [reply packages/vite-plugin-checker/src/checkers/vueTsc/languagePlugins.js:29]: Sure, will do later

**Comment by so1ve** [comment]
Invalid back references breaks dts build, any thoughts?

**Comment by fi3ework** [comment]
> Invalid back references breaks dts build, any thoughts?

Just follow the new version of typescript's instruction and change to `const myRegexp = /([^\s'"]([^\s'"]*(['"])([^\x03]*?)\3)+[^\s'"]*)|[^\s'"]+|(['"])([^\x05]*?)\5/gi` would be fine.

**Comment by fi3ework** [comment]
I also found that `multiple-hmr` and `multiple-reload` test case has some existing flaw which will break in this PR as it's using the project's thought ESLint config. I think it could be rewritten based on `eslint-default` and add one line in the `main.ts` to trigger TS error. And update `vite.config.ts` alongside is enough. And the snapshot could be updated totally.

```diff
import { text } from './text'

+ let count: string = 0
var hello = 'Hello'

const rootDom = document.querySelector('#root')!
rootDom.innerHTML = hello + text

export {}

```

```diff
import { defineConfig } from 'vite'
import checker from 'vite-plugin-checker'

export default defineConfig({
  plugins: [
    checker({
+      typescript: true,
      eslint: {
        lintCommand: 'eslint ./src --ext .ts',
      },
    }),
  ],
})
```

**Comment by fi3ework** [comment]
> I suppose \x03 is hex while \3 is a back reference?

Guess we could `ts-expect-error` as of https://github.com/microsoft/TypeScript/issues/58416.

File: packages/vite-plugin-checker/src/checkers/vueTsc/languagePlugins.cts [hunk 2]
```diff
@@ -0,0 +1,40 @@
+import type ts from 'typescript'
+import * as vue from '@vue/language-core'
```
Comment (johnsoncodehk) [inline packages/vite-plugin-checker/src/checkers/vueTsc/languagePlugins.cts:2]: `@vue/language-core` can be used from `vue-tsc` using something like this.

```suggestion
let vueTscDir = require.resolve('vue-tsc/package.json');
vueTscDir = vueTscDir.substring(0, vueTscDir.lastIndexOf('/'));
const vue: typeof import('@vue/language-core') = require(require.resolve('@vue/language-core', { paths: [vueTscDir] }));
```

**Comment by so1ve** [comment]
TODO: remove the dependency

File: packages/vite-plugin-checker/src/checkers/vueTsc/languagePlugins.js (hunk 1 above)
Comment (so1ve) [reply packages/vite-plugin-checker/src/checkers/vueTsc/languagePlugins.js]: I no longer use ts for that file(again) because tsup runs builds in parallel and I can't control who runs first, causing build failures. Please let me know if you've figured out a solution.

**Comment by so1ve** [comment]
Hi @fi3ework I couldn't get the e2e tests work since my machine is Windows. Could you please update the snapshots? thx

**Comment by fi3ework** [comment]
Awesome work. I made some fix, including:

- update legacy test case
- update snapshot
- fix CJS artifact (a bit hacky)
- stop running `vti` as it breaks in the new version, https://github.com/vuejs/vetur/issues/3686.

The test could pass all on my Mac except: build will fail on `playground/vue-tsc-vue3-ts4`. I don't know if it's the compatibility issue between vue-tsc and typescript. If so, we could drop the support of ts4.

Thanks again for the hard work, really impressive.

**Comment by fi3ework** [comment]
Still a bit struggle with Windows path on CI 😅, luckily, other CI passed.

**Comment by fi3ework** [comment]
@so1ve Could you help to check the Windows CI issue, it's relatively slow for me to test it on CI and I can't reach my Windows machine until next week. 🥺

**Comment by so1ve** [comment]
Hi @fi3ework, I don't have enough time to work on windows tests recently, but I can work on this issue in two days. How about we merge this PR first, and then I will submit another PR to fix it?

**Comment by fi3ework** [comment]
> Hi @fi3ework, I don't have enough time to work on windows tests recently, but I can work on this issue in two days. How about we merge this PR first, and then I will submit another PR to fix it?

Sure, I'll merge this PR tonight (I still want to try to Windows CI once 🥲).

**Comment by fi3ework** [comment]
GitHub is down https://www.githubstatus.com/incidents/9vwllhs2w1kj, I can't merge the PR right now. It's late tonight, I'll try to merge this PR tomorrow morning.

Google Chrome 2024-06-29 02 07 03

File: packages/vite-plugin-checker/src/checkers/vueTsc/languagePlugins.cjs [hunk 3]
```diff
@@ -0,0 +1,45 @@
+const path = require('path')
+const { removeEmitGlobalTypes } = require('vue-tsc')
+
+const vueTscDir = path.dirname(require.resolve('vue-tsc/package.json'))
+const vue = /** @type {typeof import('@vue/language-core')} */ (
+  require(require.resolve('@vue/language-core', { paths: [vueTscDir] }))
```
Comment (fi3ework) [inline packages/vite-plugin-checker/src/checkers/vueTsc/languagePlugins.cjs:6]: `@vue/language-core` is from the dependency `vue-ts`. So in a `hoist=false` enabled pnpm project. We can't reach `@vue/language-core` from `vite-plugin-checker` as it's a phantom dependency. I'd not prefer to require user to install `@vue/language-core` to dependencies again.

So based on current implementation, I think it's better to resolve `vue-tsc` first, then resolve `@vue/language-core` afterward.

We could fix this in the next PR.

**Comment by fi3ework** [comment]
@so1ve Thanks for the hard work, I really appreciate that. Looking forward to releasing this after fixing the left comment.

File: packages/vite-plugin-checker/src/checkers/vueTsc/languagePlugins.cjs (hunk 3 above)
Comment (fi3ework) [reply packages/vite-plugin-checker/src/checkers/vueTsc/languagePlugins.cjs:6]: Oh, it's already in the current implementation. I made this mistake comment by just seeing the dev dep of `@vue/language-core`.

**Comment by armano2** [comment]
windows test seem to be failing due to [jest-serializer-path](https://github.com/tribou/jest-serializer-path/blob/master/lib/index.js) normalization, path drive path is replaced with `val => val.replace(/[a-zA-Z]:\\/g, "\\")` and this seem to not be present in https://github.com/fi3ework/vite-plugin-checker/blob/56761d092f4c80f321da96bb1bab755f10edc45c/playground/serializers.ts

**Comment by so1ve** [comment]
Hi @fi3ework, yes, we don't support ts 4. We rely on ts 5 specific apis.

**Comment by fi3ework** [comment]
@so1ve Hmm, I'm wondering why peer dep is set `*` of `vue-tsc`

**Comment by so1ve** [comment]
Yeah, it would be better to point it to `^5`. Will do, thanks!

File: packages/vite-plugin-checker/package.json [hunk 4]
```diff
@@ -40,14 +40,14 @@
   "homepage": "https://github.com/fi3ework/vite-plugin-checker",
   "dependencies": {
     "@babel/code-frame": "^7.12.13",
+    "@volar/typescript": "^2.3.0",
```
Comment (armano2) [inline packages/vite-plugin-checker/package.json:43]: q: is there a reason why `@volar/typescript` is now added to `dependencies`?

```
+-- vite-plugin-checker@0.7.0
| `-- @volar/typescript@2.3.4
|   `-- @volar/language-core@2.3.4
`-- vue-tsc@2.0.24
  +-- @volar/typescript@2.4.0-alpha.5
  | `-- @volar/language-core@2.4.0-alpha.5
  `-- @vue/language-core@2.0.24
    `-- @volar/language-core@2.4.0-alpha.5
```

Comment (so1ve) [reply packages/vite-plugin-checker/package.json:43]: Just realized it can use the same approach to import `@volar/typescript` from `vue-tsc`. I'll fix it.

Comment (so1ve) [reply packages/vite-plugin-checker/package.json:43]: #333
